[package]
name = "automorph"
version = "1.0.8"
description = "AutoMorph Tauri Desktop Application"
authors = ["Human Augment Analytics"]
edition = "2021"

[lib]
name = "lizard_morph_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
