import type { ResolvedTheme } from "../contexts/ThemeContext";
import { getTokens } from "../contexts/themeTokens";

export function getMeasurementsAndScalePanelStyles(theme: ResolvedTheme) {
  const t = getTokens(theme);
  const isDark = theme === "dark";
  return {
    modalOverlay: {
      position: "fixed" as const,
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      zIndex: 999,
    },
    modalContent: {
      position: "fixed" as const,
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      backgroundColor: isDark ? "#2c2c2c" : "#ffffff",
      padding: "25px",
      borderRadius: "10px",
      boxShadow: `0 5px 15px ${isDark ? "rgba(0,0,0,0.5)" : "rgba(0,0,0,0.3)"}`,
      zIndex: 1000,
      color: t.text,
      width: "90%",
      maxWidth: "600px",
      maxHeight: "80vh",
      overflowY: "auto" as const,
    },
    modalHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: `1px solid ${isDark ? "#444" : "#ddd"}`,
      paddingBottom: "15px",
      marginBottom: "20px",
    },
    closeButton: {
      background: "transparent",
      border: "none",
      color: t.text,
      fontSize: "28px",
      cursor: "pointer",
    },
    modalBody: {
      paddingTop: "10px",
    },
    container: {
      backgroundColor: isDark ? "#333" : "#f5f5f5",
      padding: "15px",
      borderRadius: "8px",
      color: t.text,
      margin: "10px",
    },
    title: {
      margin: "0 0 15px 0",
      fontSize: "18px",
      borderBottom: `1px solid ${isDark ? "#555" : "#ddd"}`,
      paddingBottom: "10px",
    },
    formGroup: {
      marginBottom: "15px",
      display: "flex",
      alignItems: "center",
    },
    label: {
      marginRight: "10px",
      minWidth: "80px",
    },
    select: {
      flex: 1,
      padding: "8px",
      borderRadius: "4px",
      border: `1px solid ${isDark ? "#555" : "#ccc"}`,
      backgroundColor: isDark ? "#444" : "#fff",
      color: t.text,
    },
    input: {
      flex: 1,
      padding: "8px",
      borderRadius: "4px",
      border: `1px solid ${isDark ? "#555" : "#ccc"}`,
      backgroundColor: isDark ? "#444" : "#fff",
      color: t.text,
    },
    infoText: {
      marginTop: "10px",
      fontSize: "14px",
      color: t.textMuted,
    },
    emptyState: {
      textAlign: "center" as const,
      color: t.textMuted,
      padding: "20px 0",
    },
    measurementItem: {
      border: `1px solid ${isDark ? "#444" : "#ddd"}`,
      borderRadius: "6px",
      padding: "15px",
      marginBottom: "15px",
    },
    measurementHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "10px",
    },
    measurementLabel: {
      fontWeight: "bold" as const,
      fontSize: "16px",
    },
    deleteButton: {
      backgroundColor: "#c0392b",
      color: "white",
      border: "none",
      borderRadius: "4px",
      padding: "5px 10px",
      cursor: "pointer",
    },
    distanceDisplay: {
      marginTop: "10px",
      padding: "10px",
      backgroundColor: isDark ? "#2c2c2c" : "#e8e8e8",
      borderRadius: "4px",
      textAlign: "center" as const,
      fontWeight: "bold" as const,
    },
    addButton: {
      width: "100%",
      padding: "12px",
      backgroundColor: "#27ae60",
      color: "white",
      border: "none",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "16px",
      marginTop: "10px",
    },
    sectionTitle: {
      fontSize: "20px",
      fontWeight: "bold" as const,
      color: t.text,
      borderBottom: "2px solid #4CAF50",
      paddingBottom: "8px",
      marginBottom: "20px",
      marginTop: "20px",
    },
  };
}
