export const MeasurementsAndScalePanelStyles = {
  modalOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    zIndex: 999,
  },
  modalContent: {
    position: "fixed" as const,
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#2c2c2c",
    padding: "25px",
    borderRadius: "10px",
    boxShadow: "0 5px 15px rgba(0, 0, 0, 0.5)",
    zIndex: 1000,
    color: "#e0e0e0",
    width: "90%",
    maxWidth: "600px",
    maxHeight: "80vh",
    overflowY: "auto" as const,
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #444",
    paddingBottom: "15px",
    marginBottom: "20px",
  },
  closeButton: {
    background: "transparent",
    border: "none",
    color: "#e0e0e0",
    fontSize: "28px",
    cursor: "pointer",
  },
  modalBody: {
    paddingTop: "10px",
  },
  container: {
    backgroundColor: "#333",
    padding: "15px",
    borderRadius: "8px",
    color: "white",
    margin: "10px",
  },
  title: {
    margin: "0 0 15px 0",
    fontSize: "18px",
    borderBottom: "1px solid #555",
    paddingBottom: "10px",
  },
  formGroup: {
    marginBottom: "15px",
    display: "flex",
    alignItems: "center",
  },
  label: {
    marginRight: "10px",
    minWidth: "80px",
  },
  select: {
    flex: 1,
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #555",
    backgroundColor: "#444",
    color: "white",
  },
  input: {
    flex: 1,
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #555",
    backgroundColor: "#444",
    color: "white",
  },
  infoText: {
    marginTop: "10px",
    fontSize: "14px",
    color: "#a0a0a0",
  },
  emptyState: {
    textAlign: "center" as const,
    color: "#888",
    padding: "20px 0",
  },
  measurementItem: {
    border: "1px solid #444",
    borderRadius: "6px",
    padding: "15px",
    marginBottom: "15px",
  },
  measurementHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  measurementLabel: {
    fontWeight: "bold" as const,
    fontSize: "16px",
  },
  deleteButton: {
    backgroundColor: "#c0392b",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "5px 10px",
    cursor: "pointer",
  },
  distanceDisplay: {
    marginTop: "10px",
    padding: "10px",
    backgroundColor: "#2c2c2c",
    borderRadius: "4px",
    textAlign: "center" as const,
    fontWeight: "bold" as const,
  },
  addButton: {
    width: "100%",
    padding: "12px",
    backgroundColor: "#27ae60",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "16px",
    marginTop: "10px",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "bold" as const,
    color: "#e0e0e0",
    borderBottom: "2px solid #4CAF50",
    paddingBottom: "8px",
    marginBottom: "20px",
    marginTop: "20px",
  },
};
