global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'flask-app'
    static_configs:
      - targets: ['172.17.0.1:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'system-metrics'
    static_configs:
      - targets: ['172.17.0.1:3000']
    metrics_path: '/system/metrics'
    scrape_interval: 10s 