apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USERNAME}
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_PASSWORD}
    jsonData:
      tlsSkipVerify: true
    isDefault: true 